//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\UltraVP")]
        public string UltraVPPath {
            get {
                return ((string)(this["UltraVPPath"]));
            }
            set {
                this["UltraVPPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\Visual Pinball\\Tables")]
        public string VPTablePath {
            get {
                return ((string)(this["VPTablePath"]));
            }
            set {
                this["VPTablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Media\\Visual Pinball\\Backglass Images")]
        public string VPBackglassImagePath {
            get {
                return ((string)(this["VPBackglassImagePath"]));
            }
            set {
                this["VPBackglassImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Media\\Visual Pinball\\Table Images")]
        public string VPTableImagePath {
            get {
                return ((string)(this["VPTableImagePath"]));
            }
            set {
                this["VPTableImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Media\\Visual Pinball\\Wheel Images")]
        public string VPWheelImagePath {
            get {
                return ((string)(this["VPWheelImagePath"]));
            }
            set {
                this["VPWheelImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\Future Pinball\\Tables")]
        public string FPTablePath {
            get {
                return ((string)(this["FPTablePath"]));
            }
            set {
                this["FPTablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Media\\Future Pinball\\Backglass Images")]
        public string FPBackglassImagePath {
            get {
                return ((string)(this["FPBackglassImagePath"]));
            }
            set {
                this["FPBackglassImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Media\\Future Pinball\\Table Images")]
        public string FPTableImagePath {
            get {
                return ((string)(this["FPTableImagePath"]));
            }
            set {
                this["FPTableImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Media\\Future Pinball\\Wheel Images")]
        public string FPWheelImagePath {
            get {
                return ((string)(this["FPWheelImagePath"]));
            }
            set {
                this["FPWheelImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Media\\Future Pinball\\Table Videos")]
        public string FPTableVideoPath {
            get {
                return ((string)(this["FPTableVideoPath"]));
            }
            set {
                this["FPTableVideoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Media\\Visual Pinball\\Table Videos")]
        public string VPTableVideoPath {
            get {
                return ((string)(this["VPTableVideoPath"]));
            }
            set {
                this["VPTableVideoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".fpt")]
        public string FPTableExtension {
            get {
                return ((string)(this["FPTableExtension"]));
            }
            set {
                this["FPTableExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".vpt")]
        public string VPTableExtension {
            get {
                return ((string)(this["VPTableExtension"]));
            }
            set {
                this["VPTableExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".f4v")]
        public string VideoExtension {
            get {
                return ((string)(this["VideoExtension"]));
            }
            set {
                this["VideoExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".png")]
        public string ImageExtension {
            get {
                return ((string)(this["ImageExtension"]));
            }
            set {
                this["ImageExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".uvp")]
        public string UltraVPExtension {
            get {
                return ((string)(this["UltraVPExtension"]));
            }
            set {
                this["UltraVPExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TableVideoRequired {
            get {
                return ((bool)(this["TableVideoRequired"]));
            }
            set {
                this["TableVideoRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Databases\\Future Pinball\\Future Pinball.xml")]
        public string FPDBPath {
            get {
                return ((string)(this["FPDBPath"]));
            }
            set {
                this["FPDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Pinball\\HyperPin\\Databases\\Visual Pinball\\Visual Pinball.xml")]
        public string VPDBPath {
            get {
                return ((string)(this["VPDBPath"]));
            }
            set {
                this["VPDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UltraVPRequired {
            get {
                return ((bool)(this["UltraVPRequired"]));
            }
            set {
                this["UltraVPRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TableImageRequired {
            get {
                return ((bool)(this["TableImageRequired"]));
            }
            set {
                this["TableImageRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BackglassImageRequired {
            get {
                return ((bool)(this["BackglassImageRequired"]));
            }
            set {
                this["BackglassImageRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WheelImageRequired {
            get {
                return ((bool)(this["WheelImageRequired"]));
            }
            set {
                this["WheelImageRequired"] = value;
            }
        }
    }
}
